Functional module
clearly-essilor-group-canada/clearly-test pull request #7
Opened 2021-11-03 16:19 UTC by justinpancho-clearly

2021-11-03 20:01 UTC, haroldcork-clearly requested changes
A couple of changes to look at.  Also - it would be good if ITP-6935 contained details about the functionality that is being added/tested

2021-11-03 21:10 UTC, justinpancho-clearly commented on web/src/main/java/clearly/web/selenium/pages/EyeglassCategoryPage.java
> +    }
thanks good catch

2021-11-03 21:12 UTC, justinpancho-clearly commented on web/src/main/java/clearly/web/selenium/pages/CartPage.java
> +        }
With the way the code works for Actions, it will throw an exception after the timeout so we don't need to throw exceptions all over the code base to avoid clutter like the old way

2021-11-04 15:26 UTC, haroldcork-clearly commented on web/src/main/java/clearly/web/selenium/pages/CartPage.java
> +        }
Then maybe we don't want the check for isEmpty() first?  To me it looks like if the button is not there,  the isEmpty() will stop the attempt to clickElement - so no timeout would occur and the step will pass.  Or is the timeout coming from somewhere else?

2021-11-04 16:11 UTC, justinpancho-clearly commented on web/src/main/java/clearly/web/selenium/pages/CartPage.java
> +        }
yes that's true just pushed it

2021-11-04 22:24 UTC, haroldcork-clearly commented on web/src/main/java/clearly/web/selenium/pages/EyeglassCategoryPage.java
> +    }
Hey @justinpancho-clearly this change looks good.  I think you should probably do something similar with isSortedLowToHigh()

2021-11-04 22:47 UTC, haroldcork-clearly requested changes
A few minor suggestions - I am okay with you merging after addressing without an additional review.

2021-11-04 22:47 UTC, haroldcork-clearly commented on web/src/test/resources/features/cdp_filter/color_filter.feature
> +    When I select the first "color" filter
I think the format is Given / When / Then.  
'Given' is the initial condition, 'When' is an action and 'Then' is the result

2021-11-04 22:47 UTC, haroldcork-clearly commented on web/src/test/resources/features/functional/top_nav_menu.feature
> +    And I click the heading to "contact-lenses"
When I click the heading to "eyewear"
Then I click the heading to "contact-lenses"

2021-11-04 22:47 UTC, haroldcork-clearly commented on web/src/test/resources/features/functional/my_fit_measurements.feature
> +    And I enter myfit measurements "51" "14" "135"
Then I enter myfit measurements "51" "14" "135"

2021-11-04 22:47 UTC, haroldcork-clearly commented on web/src/main/java/clearly/web/cucumber/definitions/EyeglassCategoryPageDefinitions.java
> +
if you are going to merge this in - you should probably just add code to throw an error so it doesn't get missed

2021-11-05 16:03 UTC, merged